name: Sync to Hugging Face Space

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        lfs: true

    - name: Push to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
        # Add Hugging Face remote (if not exists)
        git remote add hf https://huggingface.co/spaces/danielleonte/Science-Query || true
        
        # Set up authentication
        git remote set-url hf https://user:$HF_TOKEN@huggingface.co/spaces/danielleonte/Science-Query
        
        # Push to Hugging Face
        git push --force hf main 